changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: 安全与可靠性
      labels: [security, reliability]
    - title: 功能
      labels: [enhancement]
    - title: 修复
      labels: [bug]
    - title: 其他
      labels: ["*"]
