"""
Resume module models — AI-generated resumes and version management.

Group1 domain: AI简历 + AI模拟面试
"""

from __future__ import annotations

from sqlalchemy import DateTime, ForeignKey, Integer, JSON, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from ...db.base import Base, TimestampMixin


class GeneratedResume(Base, TimestampMixin):
    """An AI-generated resume output for a student targeting a specific job.

    Each resume is generated by AI based on student profile, target job JD,
    and student's verified evidence. Multiple versions can exist for different
    jobs or iterations of the same resume.
    """

    __tablename__ = "generated_resumes"

    id: Mapped[str] = mapped_column(String(64), primary_key=True, comment="UUID主键")
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=False, index=True, comment="学生用户ID"
    )
    student_profile_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("student_profiles.id"), nullable=True, comment="学生档案ID"
    )
    career_job_id: Mapped[str | None] = mapped_column(
        String(64), ForeignKey("career_jobs.id"), nullable=True, index=True, comment="目标岗位ID"
    )
    job_title: Mapped[str | None] = mapped_column(
        String(160), nullable=True, comment="岗位名称（冗余，方便展示）"
    )
    company: Mapped[str | None] = mapped_column(
        String(160), nullable=True, comment="公司名称（冗余）"
    )
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default="1", comment="版本号，同一岗位多版本"
    )
    template_id: Mapped[str | None] = mapped_column(
        String(64), nullable=True, comment="使用的简历模板ID"
    )
    title: Mapped[str] = mapped_column(
        String(200), nullable=False, comment="简历标题，如「张三-后端开发-字节跳动」"
    )
    raw_content: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, comment="AI生成的完整简历结构化内容"
    )
    rendered_text: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="渲染后的纯文本简历"
    )
    rendered_html: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="渲染后的HTML简历"
    )
    ats_score: Mapped[int | None] = mapped_column(
        Integer, nullable=True, comment="ATS兼容性评分 0-100"
    )
    ats_feedback: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, comment="ATS优化建议"
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="draft", server_default="'draft'",
        comment="状态: draft | completed | archived"
    )
    is_current: Mapped[bool] = mapped_column(
        "is_current", Integer, nullable=False, default=0, server_default="0",
        comment="是否当前使用版本"
    )
    source_evidence_ids: Mapped[list | None] = mapped_column(
        JSON, nullable=True, comment="引用的证据ID列表"
    )
    generated_by: Mapped[str | None] = mapped_column(
        String(80), nullable=True, comment="生成模型: deepseek / glm / ..."
    )
    generation_config: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, comment="生成配置参数"
    )

    __table_args__ = (
        {"comment": "AI生成简历"}
    )


class ResumeTemplate(Base, TimestampMixin):
    """Resume template definition — layout, style, sections configuration."""

    __tablename__ = "resume_templates"

    id: Mapped[str] = mapped_column(String(64), primary_key=True, comment="UUID主键")
    name: Mapped[str] = mapped_column(String(120), nullable=False, comment="模板名称")
    category: Mapped[str | None] = mapped_column(
        String(40), nullable=True, comment="分类: general | tech | academic | creative"
    )
    description: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="模板描述"
    )
    preview_image_key: Mapped[str | None] = mapped_column(
        String(500), nullable=True, comment="预览图COS key"
    )
    layout_config: Mapped[dict] = mapped_column(
        JSON, nullable=False, comment="布局配置JSON"
    )
    style_config: Mapped[dict] = mapped_column(
        JSON, nullable=False, comment="样式配置JSON（颜色、字体等）"
    )
    section_definitions: Mapped[dict] = mapped_column(
        JSON, nullable=False, comment="简历段落定义（哪些段、顺序）"
    )
    is_default: Mapped[bool] = mapped_column(
        "is_default", Integer, nullable=False, default=0, server_default="0",
        comment="是否默认模板"
    )
    is_active: Mapped[bool] = mapped_column(
        "is_active", Integer, nullable=False, default=1, server_default="1",
        comment="是否启用"
    )

    __table_args__ = (
        {"comment": "简历模板"}
    )
